/*
* ==============================================================================
*  Name        : RingingTone3DPluginExports.inc
*  Part of     : RingingTone3DPlugin
*  Interface   : ?Interface_category, ?Interface_name
*  Description : ?Description
*  Version     : ?Version
*
*  Copyright (c) 2007 Nokia Corporation.
*  This material, including documentation and any related
*  computer programs, is protected by copyright controlled by
*  Nokia Corporation. All rights are reserved. Copying,
*  including reproducing, storing, adapting or translating, any
*  or all of this material requires the prior written consent of
*  Nokia Corporation. This material also contains confidential
*  information which may not be disclosed to others without the
*  prior written consent of Nokia Corporation.
* ==============================================================================
*/
// To get the APP_LAYER_SYSTEMINCLUDE-definition
#include <platform_paths.hrh>

#ifndef RINGINGTONE3DPLUGINEXPORTS_INC
#define RINGINGTONE3DPLUGINEXPORTS_INC

// 3D patterns for target device
../data/patterns/1circular.xml	        z:/resource/3DTones/1circular.xml
../data/patterns/2flyby.xml		z:/resource/3DTones/2flyby.xml
../data/patterns/3zigzag.xml		z:/resource/3DTones/3zigzag.xml
../data/patterns/4meander.xml		z:/resource/3DTones/4meander.xml
../data/patterns/5random.xml		z:/resource/3DTones/5random.xml

#endif      // RINGINGTONE3DPLUGINEXPORTS_INC

// End of File
